#!/usr/bin/env python

import sys, string
import alignment

# Command-line arguments
f1 = sys.argv[1]
f1 = f1
seq1 = string.strip(f1)

#f2 = open(sys.argv[2], 'r')
f2 = sys.argv[2]
seq2 = string.strip(f2)

print(seq1)
print(seq2)
alignment.needle(seq1, seq2)
